import Head from 'next/head'
import { Reveal } from 'react-gsap';

import BgStripe from '../components/bgStripe';
import { InView } from 'react-intersection-observer';
import { useState, useEffect } from 'react';
import { Homepage } from '../sections/Homepage';
import { About } from '../sections/About';
import { FadeInLeft, FadeInRight, FadeToBottom, FadeToTop } from '../global/animations';
import { ThankYou } from '../sections/ThankYou';
import Cursor from '../components/Cursor';
const data = [
  {
    uid: 'area-hifi',
    name: 'Area Hifi',
    textColor: 'white',
    image1: '/projects/project-1-1.png',
    image2: '/projects/project-1-2.png',
    image3: '/projects/project-1-3.png',
    fullImage: '',
    bgColor: '#262C26'
  },
  {
    uid: 'fashion',
    name: 'The Fashion Pulpit',
    textColor: 'white',
    image1: '/projects/project-2-1.png',
    image2: '/projects/project-2-2.png',
    image3: '/projects/project-2-3.png',
    fullImage: '',
    bgColor: '#AE5E9C'
  },
  {
    uid: 'sweatshop',
    name: 'Sweatshop Union',
    textColor: 'black',
    image1: '/projects/project-3-1.png',
    image2: '/projects/project-3-2.png',
    image3: '/projects/project-3-3.png',
    fullImage: '',
    bgColor: '#C0DFC8'
  }
]
export default function Home() {
  const [activeProject, setActiveProject] = useState(data[0]);
  const setUid = (inView, proj) => {
    if (inView) {
      setActiveProject((data.filter(x => x.uid == proj))[0])
      return;
    }
  };

  return (
    <div>
      <Head>
        <title>Myra Isidro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500&display=swap" rel="stylesheet" />
      </Head>
      <main>


        <div className="project-details" style={{ color: activeProject.textColor }}>
          <div className="top-menu">
            <div>
              <p>Web Design & Development</p>
              <p>{activeProject.name}</p>
            </div>
            <div>
              <p>Adobe XD</p>
            </div>
          </div>
          <a href="#">View Full Page</a>
        </div>
        <Homepage />
        <About />

        {
          data.map(prj => {
            const {
              image1,
              image2,
              image3,
              // bgColor,
              uid,
            } = prj;
            return (
              <div key={uid}>
                  <InView className="section project" as="div" onChange={inView => setUid(inView, uid)} threshold="0.5">
                      <img src={image1} alt="" className="project__image-1" />
                
                      <img src={image2} alt="" className="project__image-2" />
                  
                      <img src={image3} alt="" className="project__image-3" />
                  </InView>
              </div>
            )
          })
        }
        <BgStripe bgColor={activeProject.bgColor} stripeColor="#ffffff33" fixed />
        <ThankYou/>
      </main>
      <Cursor/>
    </div>
  )
}
