import Head from 'next/head'
import Image from 'next/image'
import BgStripe from '../components/bgStripe';
import myraPic from './../public/myra.png';
import { InView } from 'react-intersection-observer';
import { useState, useEffect } from 'react';
const data = [
  {
    uid: 'area-hifi',
    name: 'Area Hifi',
    textColor: 'white',
    image1: '/projects/project-1-1.png',
    image2: '/projects/project-1-2.png',
    image3: '/projects/project-1-3.png',
    fullImage: '',
    bgColor: '#262C26'
  },
  {
    uid: 'fashion',
    name: 'The Fashion Pulpit',
    textColor: 'white',
    image1: '/projects/project-2-1.png',
    image2: '/projects/project-2-2.png',
    image3: '/projects/project-2-3.png',
    fullImage: '',
    bgColor: '#AE5E9C'
  },
  {
    uid: 'sweatshop',
    name: 'Sweatshop Union',
    textColor: 'black',
    image1: '/projects/project-3-1.png',
    image2: '/projects/project-3-2.png',
    image3: '/projects/project-3-3.png',
    fullImage: '',
    bgColor: '#C0DFC8'
  }
]
export default function Home() {
  const [activeProject, setActiveProject] = useState(data[0]);
  const setUid = (inView, proj) => {
    if (inView) {
      setActiveProject((data.filter(x => x.uid == proj))[0])
      return;
    }
  };



 

  return (
    <div>
      <Head>
        <title>Myra Isidro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500&display=swap" rel="stylesheet" />
      </Head>

      <main>
      <div className="project-details" style={{color: activeProject.textColor}}>
          <div className="top-menu">
          <div>
          <p>Web Design & Development</p>
          <p>{activeProject.name}</p>
          </div>
          <div>
            <p>Adobe XD</p>
          </div>
          </div>
          <a href="#">View Full Page</a>
          
        </div>
        <section className="section homepage">
          <BgStripe />
          <div className="homepage__container">
            <div className="grid">
              <h1 className="hello">Hello,</h1>
              <h1 className="im">I’m</h1>
              <span className="gd">
                graphic designer<br />
                ui/ux designer</span>
              <h1 className="myra">Myra Isidro</h1>
            </div>

            <p>And here's my portfolio</p>
          </div>
        </section>
        <section className="section about">
          <div className="about__container">
            <div className="about-a">
              <h2>Myra Isidro</h2>

              <h4>myraisidro4@gmail.com</h4>
              <h4>+63 927 2577 989</h4>
              <h4>linkedin.com/in/myraisidro/</h4>
            </div>
            <div className="about-b">
              <Image src={myraPic}
                layout="fill"
                objectFit="contain"
                objectPosition="bottom left"
                alt="Myra"
              />
            </div>
            <div className="about-c">
              <ul>
                <li>behance.net/myraisidro_designs</li>
                <li>Instagram.com/typo.designs_</li>
              </ul>
            </div>
            <div className="about-d">
              <p>
                I'm a Freelance Graphic & UI/UX Designer for more than 2 years now. Ever since I started designing I still keep on looking forward to a lot more challenges & experiences I can get on this field, that can contribute to my personal growth and to have share it to anyone whom I can future work with.
              </p>
            </div>
          </div>
        </section>

        {
          data.map(prj => {
            const {
              image1,
              image2,
              image3,
              // bgColor,
              uid,
            } = prj;
            return (
              <InView className="section project" as="div" onChange={inView => setUid(inView, uid)} threshold="0.5">
                {/* <h1>Project 1</h1> */}
                <img src={image1} alt="" className="project__image-1" />
                <img src={image2} alt="" className="project__image-2" />
                <img src={image3} alt="" className="project__image-3" />
              </InView>
            )
          })
        }
        <BgStripe bgColor={activeProject.bgColor} stripeColor="#ffffff33" fixed/>
        <section className="section thankyou">
         <h1>Thank you</h1>
         <p>FOR MORE SAMPLE WORKS, PLEASE CHECK MY BEHANCE & INSTAGRAM PROFILE AT</p>
         <p>behance.net/myraisidro_designs</p>
         <p>Instagram.com/typo.designs_</p>
        </section>
      </main>
      
    </div>
  )
}
